version: "3"
services:
  wordpress:
    image: wordpress
    ports: 
      - "7000:80"
    depends_on:
      - mysql
    environment:
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: "admin123"
        WORDPRESS_DB_NAME: wordpress
  mysql:
    image: "mysql:5.7"
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "admin123"
    volumes:
      - ./mysql:/var/lib/mysql
